import { test,expect } from "@playwright/test";

test("artist discovery and comparison survive filters and reloads",async({page})=>{
  await page.goto("/search?q=Test+Artist");
  await page.getByRole("region",{name:"Artists",exact:true}).getByRole("link").click();
  await expect(page.getByRole("heading",{name:"Test Artist",level:1})).toBeVisible();
  await expect(page.locator("article")).toHaveCount(1);
  await page.locator("article").getByRole("button",{name:"Compare",exact:true}).click();
  await page.getByRole("navigation",{name:"Wiki sections"}).getByRole("link",{name:"Variants",exact:true}).click();
  await page.getByRole("combobox",{name:"Release status",exact:true}).selectOption("unreleased");
  await page.getByRole("button",{name:"Apply filters"}).click();
  await expect(page.getByRole("complementary",{name:"Variant comparison tray"})).toContainText("Compare 1/2");
  await page.locator("article").getByRole("button",{name:"Compare",exact:true}).click();
  await page.reload();
  await page.getByRole("link",{name:"Compare artwork"}).click();
  await expect(page.locator("article")).toHaveCount(2);
  await expect(page.locator("article").getByText("Unreleased preview",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Copy comparison link"})).toBeVisible();
  await page.screenshot({path:test.info().outputPath("compare.png"),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole("button",{name:"Clear selection"}).click();
  await expect(page.getByRole("complementary",{name:"Variant comparison tray"})).toHaveCount(0);
  await page.goto("/wiki/compare?a=bad&b=bad");
  await expect(page.getByText("Choose two different variants",{exact:false})).toBeVisible();
});

test("collection persists and shared wishlist excludes owned artwork and can be revoked",async({page,browser,baseURL})=>{
  await page.goto("/wiki/my-collection");
  await page.getByRole("link",{name:"Sign in with Discord"}).click();
  await expect(page.getByRole("heading",{name:"My variant collection",exact:true})).toBeVisible();
  // Desktop and mobile projects use the same stub account; start this journey from a known state.
  for(const variant of ["released-example","upcoming-example"])await page.request.put("/api/collection",{data:{card:"TestCard1",variant,status:null}});
  await page.request.delete("/api/collection/share");
  await page.goto("/wiki/variants");
  await page.locator("article").getByRole("button",{name:"Owned",exact:true}).click();
  await expect(page.locator("article").getByRole("button",{name:"Owned",exact:true})).toHaveAttribute("aria-pressed","true");
  await page.reload();
  await expect(page.locator("article").getByRole("button",{name:"Owned",exact:true})).toHaveAttribute("aria-pressed","true");
  await page.getByRole("combobox",{name:"Release status",exact:true}).selectOption("unreleased");
  await page.getByRole("button",{name:"Apply filters"}).click();
  await expect(page.locator("article").getByRole("button",{name:"Owned",exact:true})).toHaveCount(0);
  await page.locator("article").getByRole("button",{name:"Wanted",exact:true}).click();
  await expect(page.locator("article").getByRole("button",{name:"Wanted",exact:true})).toHaveAttribute("aria-pressed","true");
  await page.getByRole("navigation",{name:"Wiki sections"}).getByRole("link",{name:"My collection",exact:true}).click();
  await expect(page.locator("article")).toHaveCount(2);
  await page.getByRole("button",{name:"Enable share link"}).click();
  const link=page.getByRole("link",{name:"View shared wishlist"});await expect(link).toBeVisible();
  const href=(await link.getAttribute("href"))!;
  const guest=await browser.newContext({baseURL}),guestPage=await guest.newPage();
  await guestPage.goto(href);
  await expect(guestPage.locator("article")).toHaveCount(1);
  await expect(guestPage.locator("article").getByText("Preview Artist",{exact:true})).toBeVisible();
  await expect(guestPage.locator("article").getByRole("button")).toHaveCount(0);
  expect((await guestPage.request.get("/api/collection")).status()).toBe(401);
  const privateResponse=await page.request.get("/api/collection");expect(privateResponse.headers()["cache-control"]).toContain("no-store");
  await page.screenshot({path:test.info().outputPath("my-collection.png"),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole("button",{name:"Disable sharing"}).click();
  await expect(page.getByRole("button",{name:"Enable share link"})).toBeVisible();
  await guestPage.goto(href);await expect(guestPage.getByText("Nothing here",{exact:true})).toBeVisible();
  await guest.close();
});

test("learning pages connect and interactive examples respond without overflow",async({page})=>{
  await page.emulateMedia({reducedMotion:"reduce"});
  await page.goto("/wiki");
  await expect(page.getByRole("heading",{name:"A little discovery, every day."})).toBeVisible();
  await page.getByRole("link",{name:/Can you tell who reveals first/}).click();
  await expect(page.locator("#priority")).toBeInViewport();
  await expect(page.locator("#priority").getByRole("status")).toContainText("You reveal first.");
  await page.getByRole("spinbutton",{name:"Opponent right power"}).fill("10");
  await expect(page.locator("#priority").getByRole("status")).toContainText("Opponent reveals first.");
  await page.getByRole("combobox",{name:"Snap situation"}).selectOption({label:"Second snap pending"});
  await expect(page.locator("#snapping").getByRole("status")).toContainText("−2");
  await expect(page.locator("#snapping").getByRole("status")).toContainText("±8");
  await page.getByRole("combobox",{name:"Ability type"}).selectOption("activate");
  await expect(page.locator("#abilities").getByRole("status")).toContainText("Activate can resolve.");
  await page.screenshot({path:test.info().outputPath("interaction-lab.png"),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole("link",{name:"Find a deck game plan"}).click();
  await page.getByRole("link",{name:/Destroy →/}).click();
  await expect(page.getByRole("heading",{name:"Destroy: learn the game plan"})).toBeVisible();
  await expect(page.getByRole("heading",{name:"Missing a card?"})).toBeVisible();
  await expect(page.getByRole("navigation",{name:"Breadcrumb"})).toContainText("Archetypes");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.goto("/wiki/artists");
  await expect(page.getByRole("link",{name:/Preview Artist/})).toBeVisible();
  await page.screenshot({path:test.info().outputPath("artists.png"),fullPage:true});
});
