"use client";
import { useState } from "react";
import Link from "next/link";
import { boardLeader,cubeStakes } from "@/lib/wiki/interaction-model";
const source="https://marvelsnap.helpshift.com/hc/en/3-marvel-snap/faq/";
const scenarios=[{label:"No snaps",accepted:0,pending:false},{label:"Opponent just snapped",accepted:0,pending:true},{label:"One accepted snap",accepted:1,pending:false},{label:"Second snap pending",accepted:1,pending:true},{label:"Both snaps accepted",accepted:2,pending:false}] as const;
export function InteractionLab(){
  const [powers,setPowers]=useState([[8,4,3],[5,6,2]]),[scenario,setScenario]=useState(0),[cosmo,setCosmo]=useState(true),[ability,setAbility]=useState("reveal");
  const leader=boardLeader(powers[0],powers[1]),stakes=cubeStakes(scenarios[scenario].accepted,scenarios[scenario].pending);
  return <div className="space-y-10">
    <section id="priority" aria-labelledby="priority-title" className="scroll-mt-40 rounded-2xl border border-line bg-surface/50 p-4 sm:p-6">
      <p className="text-xs font-bold uppercase tracking-widest text-accent">01 / Read the board</p><h2 id="priority-title" className="mt-3 text-2xl font-bold">Who reveals first?</h2>
      <p className="my-4 max-w-3xl text-sm leading-relaxed text-muted">Change the power at each location. Whoever is winning the board has priority. When each player leads the same number of locations, compare total power. These are illustrative totals, with no special location or card effects.</p>
      <div className="grid grid-cols-3 gap-2 sm:gap-4">{["Left","Middle","Right"].map((name,i)=><div key={name} className="min-w-0 rounded-xl border border-line bg-bg p-2 sm:p-4"><h3 className="mb-3 text-center text-xs font-bold uppercase tracking-wider">{name}</h3>{["Opponent","You"].map((label,row)=>{const index=row===0?1:0;return <label key={label} className="mb-3 block text-center text-xs text-muted">{label}<input aria-label={`${label} ${name.toLowerCase()} power`} type="number" min={-999} max={999} value={powers[index][i]} className="mt-2 block w-full min-w-0 rounded border border-line bg-surface px-1 py-3 text-center text-xl font-bold text-ink" onChange={e=>{const next=Math.max(-999,Math.min(999,Math.trunc(Number(e.target.value)||0)));setPowers(old=>old.map((line,r)=>line.map((p,c)=>r===index&&c===i?next:p)));}}/></label>;})}<p className="text-center text-xs text-accent">{powers[0][i]===powers[1][i]?"Tied":powers[0][i]>powers[1][i]?"You lead":"They lead"}</p></div>)}</div>
      <div role="status" className="mt-5 rounded-lg border border-accent/30 p-4"><strong>{leader==="tie"?"The board is tied.":leader==="you"?"You reveal first.":"Opponent reveals first."}</strong><p className="mt-2 text-sm text-muted">Your total: {powers[0].reduce((a,b)=>a+b,0)} · Opponent total: {powers[1].reduce((a,b)=>a+b,0)}. {leader==="tie"?"Power alone does not determine priority here. Check the glowing player name in the game.":"Use this information before planning an effect that must resolve first or last."}</p></div>
      <button onClick={()=>setPowers([[8,4,3],[5,6,2]])} className="mt-4 rounded border border-line px-4 py-2 text-sm">Reset board</button>
      <p className="mt-4 text-xs text-muted">Rules: <a className="underline" href={`${source}38-whose-cards-are-revealed-first-during-a-turn/`}>Reveal order</a> · <a className="underline" href={`${source}90-how-do-i-win-a-match/`}>Winning a match</a>.</p>
    </section>
    <section id="snapping" aria-labelledby="snap-title" className="scroll-mt-40 rounded-2xl border border-line bg-surface/50 p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">02 / Know the stakes</p><h2 id="snap-title" className="mt-3 text-2xl font-bold">Stay or retreat?</h2><p className="my-4 max-w-3xl text-sm leading-relaxed text-muted">A standard Ranked game on the final turn, before you end your turn. Accepted snaps have already raised the current stake; a pending opponent snap has not. Playing through the final reveal doubles the stake again. Tied games have no net cube transfer.</p>
      <label className="text-sm">Snap situation<select value={scenario} onChange={e=>setScenario(Number(e.target.value))} className="mt-2 block max-w-full rounded border border-line bg-bg p-3">{scenarios.map((s,i)=><option key={s.label} value={i}>{s.label}</option>)}</select></label>
      <div role="status" className="my-6 grid grid-cols-2 gap-4"><div className="rounded-xl border border-line bg-bg p-5"><p className="text-xs text-muted">Retreat now</p><p className="my-3 font-display text-4xl font-bold">−{stakes.retreat}</p><p className="text-xs text-muted">Cubes lost</p></div><div className="rounded-xl border border-accent/40 bg-bg p-5"><p className="text-xs text-muted">Play to showdown</p><p className="my-3 font-display text-4xl font-bold text-accent">±{stakes.showdown}</p><p className="text-xs text-muted">Cubes won or lost</p></div></div>
      <p className="text-sm text-muted">A bigger potential win also means a bigger possible loss. Compare your two-lane winning line with the opponent’s plausible finish before you accept.</p><p className="mt-4 text-xs text-muted">This example excludes mode-specific stakes, Conquest health caps and restrictions immediately after your own snap. Rules: <a className="underline" href={`${source}28-what-is-snapping/`}>Snapping</a> · <Link className="underline" href="/wiki/terminology#retreat">Retreating</Link>.</p>
    </section>
    <section id="abilities" aria-labelledby="ability-title" className="scroll-mt-40 rounded-2xl border border-line bg-surface/50 p-4 sm:p-6"><p className="text-xs font-bold uppercase tracking-widest text-accent">03 / Read the keyword</p><h2 id="ability-title" className="mt-3 text-2xl font-bold">Cosmo, On Reveal and Activate</h2><p className="my-4 max-w-3xl text-sm leading-relaxed text-muted">Cosmo is already face-up at the location and its Ongoing ability is working. Choose the type of effect you want to resolve there. The Activate card was played on an earlier turn, is still present and has not used its ability.</p>
      <div className="flex flex-wrap gap-4"><label className="text-sm">Ability type<select className="mt-2 block rounded border border-line bg-bg p-3" value={ability} onChange={e=>setAbility(e.target.value)}><option value="reveal">On Reveal</option><option value="activate">Activate</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={cosmo} onChange={e=>setCosmo(e.target.checked)}/>Cosmo active at this location</label></div>
      <div className="mx-auto my-6 max-w-sm rounded-2xl border border-line bg-bg p-6 text-center"><p className="text-xs uppercase tracking-widest text-muted">Example location</p><div className="my-4 rounded border border-line p-4 text-sm">{cosmo?"Cosmo · Ongoing active":"No active Cosmo"}</div><div className="rounded border border-accent/40 p-4 text-sm text-accent">{ability==="reveal"?"Incoming On Reveal":"Ready Activate"}</div></div>
      <p role="status" className="rounded-lg border border-accent/30 p-4 font-semibold">{cosmo&&ability==="reveal"?"On Reveal is prevented here. The card can still be played.":ability==="activate"?"Activate can resolve. Cosmo prevents On Reveal abilities, not Activate.":"On Reveal can resolve in this example."}</p>
      <p className="mt-4 text-sm leading-relaxed text-muted">An Activate ability joins your action sequence where you queue it. Queue it before a play to resolve it before that card reveals; queue it after the play to resolve it afterward. An ability that specifically triggers another effect can introduce further interactions outside this example.</p><p className="mt-4 text-xs text-muted">Source: <a className="underline" href="https://marvelsnap.com/our-first-brand-new-ability-activate/">Second Dinner’s Activate guide and FAQ</a>.</p>
    </section>
  </div>;
}
