type Shape = "cards" | "stats" | "table" | "builder" | "decks" | "wiki" | "detail" | "guide" | "gallery" | "compare";
export function PageSkeleton({ shape = "stats", label = "Loading page", header = true }: { shape?: Shape; label?: string; header?: boolean }) {
  const cards = <div className={shape === "gallery" ? "grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4" : "grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6"}>{Array.from({ length: shape === "gallery" ? 8 : 12 }, (_, i) => <div key={i} className="rounded-xl border border-line p-3"><div className="skeleton aspect-square" /><div className="skeleton mt-3 h-4 w-3/4" /><div className="skeleton mt-2 h-3 w-full" /></div>)}</div>;
  return <div role="status" aria-label={label}>
    <span className="sr-only">{label}…</span>
    <div aria-hidden="true">
      {header && <div className="mb-8 border-b border-line/60 pb-6"><div className="skeleton h-10 w-64 max-w-full" /><div className="skeleton mt-3 h-4 w-96 max-w-full" /></div>}
      {shape === "detail" ? <><div className="skeleton h-5 w-24" /><div className="mt-5 grid items-center gap-8 rounded-xl bg-surface p-6 sm:p-10 md:grid-cols-[minmax(0,320px)_1fr]"><div className="skeleton aspect-square" /><div><div className="skeleton h-3 w-24" /><div className="skeleton mt-4 h-10 w-3/4" /><div className="skeleton my-5 h-10 w-44" /><div className="skeleton h-6" /><div className="skeleton mt-3 h-6 w-2/3" /><div className="skeleton mt-6 h-11 w-36" /></div></div><div className="skeleton my-8 h-36" /></>
        : shape === "guide" ? <div className="max-w-3xl space-y-8">{Array.from({ length: 3 }, (_, i) => <div key={i}><div className="skeleton mb-4 h-7 w-1/3" /><div className="skeleton h-4" /><div className="skeleton mt-3 h-4" /><div className="skeleton mt-3 h-4 w-3/4" /></div>)}</div>
        : shape === "wiki" ? <><div className="skeleton mb-8 h-28" /><div className="skeleton mb-4 h-8 w-2/3 max-w-96" /><div className="grid gap-4 md:grid-cols-3">{Array.from({ length: 3 }, (_, i) => <div key={i} className="rounded-xl bg-surface p-5"><div className="skeleton h-4 w-1/2" /><div className="skeleton mx-auto my-5 aspect-square w-full max-w-60" /><div className="skeleton h-6 w-2/3" /><div className="skeleton mt-3 h-4" /></div>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-3">{Array.from({length:3},(_,i)=><div key={i} className="skeleton h-36" />)}</div></>
        : shape === "compare" ? <div className="grid gap-5 md:grid-cols-2">{[0,1].map((i)=><div key={i} className="rounded-xl bg-surface p-5"><div className="skeleton mx-auto aspect-square w-full max-w-96" /><div className="skeleton mt-5 h-7 w-2/3" /><div className="skeleton mt-3 h-4" /></div>)}</div>
        : shape === "builder" ? <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_380px]"><div><div className="skeleton mb-6 h-44" />{cards}</div><div className="rounded-xl border border-line p-4"><div className="skeleton mb-4 h-8 w-2/3" /><div className="grid grid-cols-4 gap-2">{Array.from({ length: 12 }, (_, i) => <div key={i} className="skeleton aspect-square" />)}</div><div className="skeleton mt-6 h-24" /><div className="skeleton mt-4 h-12" /></div></div>
        : shape === "cards" || shape === "gallery" ? <><div className="skeleton mb-6 h-24" />{cards}</>
        : shape === "decks" ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, i) => <div key={i} className="skeleton h-60" />)}</div>
        : <>{shape === "stats" && <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({ length: 4 }, (_, i) => <div key={i} className="skeleton h-24" />)}</div>}<div className="rounded-xl border border-line p-4"><div className="skeleton mb-6 h-8 w-1/3" />{Array.from({ length: 8 }, (_, i) => <div key={i} className="mb-3 grid grid-cols-[2fr_1fr_1fr] gap-6"><div className="skeleton h-7" /><div className="skeleton h-7" /><div className="skeleton h-7" /></div>)}</div></>}
    </div>
  </div>;
}
